# Generated by Django 4.1.7 on 2023-07-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("living_supermarkets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supermarket",
            name="supermarket_name",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
