# Generated by Django 4.1.7 on 2023-08-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tube",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "station_name",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "line",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        blank=True, default=None, max_length=10, null=True
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, default=None, max_length=40, null=True
                    ),
                ),
                ("long", models.FloatField(blank=True, default=None, null=True)),
                ("lat", models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
