# Generated by Django 4.1.3 on 2022-12-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tubes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tube',
            old_name='POI_lat',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='tube',
            old_name='POI_long',
            new_name='long',
        ),
    ]
