# Generated by Django 4.1.5 on 2023-11-08 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postcode", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "bathrooms_min",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "bathrooms_max",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "bedrooms_min",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "bedrooms_max",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                ("price_min", models.FloatField(blank=True, default=None, null=True)),
                ("price_max", models.FloatField(blank=True, default=None, null=True)),
                ("channel", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_gen_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
