# Generated by Django 4.1.5 on 2023-11-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead_gen_details", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchdetails",
            name="channel",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="searchdetails",
            name="postcode",
            field=models.CharField(max_length=1000),
        ),
    ]
