# Generated by Django 4.1.5 on 2023-11-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead_gen_details", "0002_alter_searchdetails_channel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchdetails",
            name="channel",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
