# Generated by Django 4.1.5 on 2023-11-09 17:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lead_gen_details", "0002_alter_searchdetails_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchdetails",
            name="area",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
