# Generated by Django 4.1.5 on 2023-11-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead_gen_details", "0003_alter_searchdetails_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchdetails",
            name="rental_additional",
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
