# Generated by Django 4.1.5 on 2023-11-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead_gen_details", "0005_alter_searchdetails_rental_additional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchdetails",
            name="rental_additional",
            field=models.CharField(blank=True, default=None, max_length=35, null=True),
        ),
    ]
