# Generated by Django 4.1.5 on 2023-11-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lead_gen_details", "0006_alter_searchdetails_rental_additional"),
    ]

    operations = [
        migrations.RenameField(
            model_name="searchdetails",
            old_name="price_max",
            new_name="rental_price_max",
        ),
        migrations.RenameField(
            model_name="searchdetails",
            old_name="price_min",
            new_name="rental_price_min",
        ),
        migrations.AddField(
            model_name="searchdetails",
            name="sales_price_max",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="searchdetails",
            name="sales_price_min",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
