# Generated by Django 4.1.5 on 2024-01-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lead_gen_details",
            "0007_rename_price_max_searchdetails_rental_price_max_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="searchdetails",
            name="subcode",
            field=models.CharField(
                blank=True, default=None, max_length=1000, null=True
            ),
        ),
        migrations.AlterField(
            model_name="searchdetails",
            name="postcode",
            field=models.CharField(
                blank=True, default=None, max_length=1000, null=True
            ),
        ),
    ]
