# Generated by Django 4.1.5 on 2023-01-26 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_property_tenure'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.PositiveIntegerField(blank=True, default=None)),
                ('prop_long', models.FloatField(blank=True, default=None, null=True)),
                ('prop_lat', models.FloatField(blank=True, default=None, null=True)),
                ('pub_name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('pub_category_value', models.FloatField(blank=True, default=None, null=True)),
                ('POI_long', models.FloatField(blank=True, default=None, null=True)),
                ('POI_lat', models.FloatField(blank=True, default=None, null=True)),
                ('adjusted_dist_km', models.FloatField(blank=True, default=None, null=True)),
                ('walking_time_mins', models.FloatField(blank=True, default=None, null=True)),
                ('property_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bars', to='properties.property')),
            ],
        ),
    ]
