# Generated by Django 4.1.5 on 2024-01-17 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True, unique=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True, unique=True
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True, unique=True
                    ),
                ),
                (
                    "looking",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True, unique=True
                    ),
                ),
                (
                    "date_onboarded",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True, unique=True
                    ),
                ),
                (
                    "link_sent",
                    models.CharField(
                        blank=True, default=None, max_length=10, null=True, unique=True
                    ),
                ),
                (
                    "link_replied",
                    models.CharField(
                        blank=True, default=None, max_length=10, null=True, unique=True
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
