# Generated by Django 4.1.5 on 2024-01-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_client_details", "0002_clientdetails_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientdetails",
            name="area",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="clientdetails",
            name="date_onboarded",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="clientdetails",
            name="first_name",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="clientdetails",
            name="last_name",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="clientdetails",
            name="link_replied",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="clientdetails",
            name="link_sent",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="clientdetails",
            name="looking",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
