# Generated by Django 4.1.5 on 2024-01-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_client_details", "0003_alter_clientdetails_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientdetails",
            name="date_onboarded",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
