# Generated by Django 4.1.5 on 2023-04-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='email_confirmation',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='long',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
