# Generated by Django 4.1.5 on 2023-04-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_emails', '0002_list_email_confirmation_list_lat_list_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='email_address',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, unique=True),
        ),
    ]
