# Generated by Django 4.1.5 on 2023-01-25 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_property_tenure'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.PositiveIntegerField(blank=True, default=None)),
                ('property_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('prop_long', models.FloatField(blank=True, default=None, null=True)),
                ('prop_lat', models.FloatField(blank=True, default=None, null=True)),
                ('cafe_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('cleansed_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('cafe_selector', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('postcode_area', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('POI_long', models.FloatField(blank=True, default=None, null=True)),
                ('POI_lat', models.FloatField(blank=True, default=None, null=True)),
                ('straight_dist_km', models.FloatField(blank=True, default=None, null=True)),
                ('adjusted_dist_km', models.FloatField(blank=True, default=None, null=True)),
                ('walking_time_mins', models.FloatField(blank=True, default=None, null=True)),
                ('driving_time_mins', models.FloatField(blank=True, default=None, null=True)),
                ('cycling_time_mins', models.FloatField(blank=True, default=None, null=True)),
                ('property_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cafes', to='properties.property')),
            ],
        ),
    ]
