# Generated by Django 4.1.5 on 2023-01-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_cafes', '0002_propertycafe_property_postcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertycafe',
            name='property_postcode',
        ),
    ]
