# Generated by Django 4.1.3 on 2022-11-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(default=None, max_length=200)),
                ('area_description', models.TextField(default=None, max_length=1000)),
                ('area_postcode', models.CharField(default=None, max_length=10)),
                ('area_image', models.CharField(default=None, max_length=250)),
            ],
        ),
    ]
