# Generated by Django 4.1.5 on 2024-01-18 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agent_client_details", "0004_alter_clientdetails_date_onboarded"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientSearches",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        blank=True, default=None, max_length=10, null=True
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "search_name",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "propertyType",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                ("garden", models.BooleanField(blank=True, default=None, null=True)),
                (
                    "size",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "bedrooms_min",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "bedrooms_max",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                ("price_min", models.IntegerField(blank=True, default=None, null=True)),
                ("price_max", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "primaries",
                    models.BooleanField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "primaries_score",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "secondaries",
                    models.BooleanField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "secondaries_score",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "parks",
                    models.BooleanField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "parks_score",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "playgrounds",
                    models.BooleanField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "playgrounds_score",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "gyms",
                    models.BooleanField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "gyms_score",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "restaurants",
                    models.BooleanField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "restaurants_score",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "pubs",
                    models.BooleanField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "pubs_score",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "tubes",
                    models.BooleanField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "tubes_score",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "supermarkets",
                    models.BooleanField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "supermarkets_score",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "ev",
                    models.BooleanField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "ev_score",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "crime",
                    models.BooleanField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "crime_score",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_saved_searches",
                        to="agent_client_details.clientdetails",
                    ),
                ),
            ],
        ),
    ]
