# Generated by Django 4.1.7 on 2023-03-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('cuisine', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('master_cuisine', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('rating', models.FloatField(blank=True, default=None, null=True)),
                ('reviews', models.FloatField(blank=True, default=None, null=True)),
                ('postcode', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('lat', models.FloatField(blank=True, default=None, null=True)),
                ('long', models.FloatField(blank=True, default=None, null=True)),
                ('source', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('url', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('postcode_area', models.CharField(blank=True, default=None, max_length=5, null=True)),
            ],
        ),
    ]
