# Generated by Django 4.1.7 on 2023-03-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='reviews',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
