# Generated by Django 4.1.7 on 2023-03-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_restaurants', '0002_alter_restaurant_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='reviews',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=6, null=True),
        ),
    ]
