# Generated by Django 4.1.7 on 2023-03-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_restaurants', '0003_alter_restaurant_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
