# Generated by Django 4.1.5 on 2023-04-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_restaurants', '0005_restaurant_city_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
