# Generated by Django 4.1.5 on 2023-04-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_restaurants', '0006_restaurant_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
