# Generated by Django 4.1.7 on 2023-08-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Borough",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borough",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "borough_description",
                    models.CharField(
                        blank=True, default=None, max_length=500, null=True
                    ),
                ),
                ("longitude", models.FloatField(blank=True, default=None, null=True)),
                ("latitude", models.FloatField(blank=True, default=None, null=True)),
                (
                    "primary_rank",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "secondary_rank",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "parks_rank",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("pubs_rank", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "pubs_count",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "restaurants_rank",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "michelin_spots",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "restaurant_count",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "crime_rank",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("ev_number", models.IntegerField(blank=True, default=None, null=True)),
                ("evs_rank", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "tube_lines",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "tube_names",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "train_names",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "borough_avg_price",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "property_price_rank",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "borough_sales_count",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "population",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "households",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "avg_income",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "borough_image",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
            ],
        ),
    ]
