# Generated by Django 4.1.7 on 2023-08-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("borough_summary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borough",
            name="borough_description",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
