# Generated by Django 4.1.7 on 2023-07-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("white_primary_details", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="primarydetail",
            name="applications",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="primarydetail",
            name="places",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="primarydetail",
            name="students",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
