# Generated by Django 4.1.7 on 2023-08-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("white_primary_details", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="primarydetail",
            name="priority_approach",
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
