# Generated by Django 4.1.7 on 2023-07-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("white_primary_details", "0002_alter_primarydetail_applications_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="primarydetail",
            name="school_name",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
