# Generated by Django 4.1.7 on 2023-07-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("white_primary_details", "0003_alter_primarydetail_school_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="primarydetail",
            name="image_url",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
