# Generated by Django 4.1.7 on 2023-07-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("white_primary_details", "0004_alter_primarydetail_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="primarydetail",
            name="religion",
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
