# Generated by Django 4.1.7 on 2023-07-05 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("postcodes", "0002_alter_postcodes_ward"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParksPostcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "postcode",
                    models.CharField(blank=True, default=None, max_length=7, null=True),
                ),
                ("distance0", models.FloatField(blank=True, default=None, null=True)),
                ("distance1", models.FloatField(blank=True, default=None, null=True)),
                ("distance2", models.FloatField(blank=True, default=None, null=True)),
                ("distance3", models.FloatField(blank=True, default=None, null=True)),
                ("distance4", models.FloatField(blank=True, default=None, null=True)),
                (
                    "park_name0",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "park_name1",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "park_name2",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "park_name3",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "park_name4",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "park_use0",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "park_use1",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "park_use2",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "park_use3",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "park_use4",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "postcode_ref",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parks_postcode",
                        to="postcodes.postcodes",
                    ),
                ),
            ],
        ),
    ]
