# Generated by Django 4.1.7 on 2023-07-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("white_greenspace_postcode", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkspostcode",
            name="park_name0",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="parkspostcode",
            name="park_name1",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="parkspostcode",
            name="park_name2",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="parkspostcode",
            name="park_name3",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="parkspostcode",
            name="park_name4",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="parkspostcode",
            name="park_use0",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="parkspostcode",
            name="park_use1",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="parkspostcode",
            name="park_use2",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="parkspostcode",
            name="park_use3",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="parkspostcode",
            name="park_use4",
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
    ]
