# Generated by Django 4.1.7 on 2023-08-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "restaurant_name",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "cuisine",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "master_cuisine",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                ("rating", models.FloatField(blank=True, default=None, null=True)),
                (
                    "reviews",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        default=None,
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        blank=True, default=None, max_length=10, null=True
                    ),
                ),
                ("latitude", models.FloatField(blank=True, default=None, null=True)),
                ("longitude", models.FloatField(blank=True, default=None, null=True)),
                (
                    "district",
                    models.CharField(
                        blank=True, default=None, max_length=40, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, default=None, max_length=40, null=True
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, default=None, max_length=150, null=True
                    ),
                ),
            ],
        ),
    ]
