# Generated by Django 4.1.7 on 2023-08-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("white_pubs_list", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publist",
            name="rank",
            field=models.CharField(blank=True, default=None, max_length=11, null=True),
        ),
    ]
