# Generated by Django 4.1.7 on 2023-03-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='living',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
