# Generated by Django 4.1.7 on 2023-10-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jwt_auth", "0006_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="company_hierarchy",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="product_tier",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
