# Generated by Django 4.1.7 on 2023-10-04 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jwt_auth", "0007_user_company_user_company_hierarchy_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="company",
        ),
        migrations.RemoveField(
            model_name="user",
            name="company_hierarchy",
        ),
    ]
