# Generated by Django 4.1.7 on 2023-03-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0007_user_living'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='living',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
