# Generated by Django 4.1.7 on 2023-10-04 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client_list", "0001_initial"),
        ("jwt_auth", "0008_remove_user_company_remove_user_company_hierarchy"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="client_list.company",
            ),
        ),
    ]
