# Generated by Django 4.1.7 on 2023-10-10 12:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jwt_auth", "0009_user_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="product_tier",
        ),
    ]
