# Generated by Django 4.1.5 on 2024-03-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jwt_auth", "0010_remove_user_product_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
    ]
