# Generated by Django 4.1.5 on 2024-03-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jwt_auth", "0011_user_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="company_name",
            field=models.CharField(max_length=100),
        ),
    ]
