# Generated by Django 4.1.5 on 2024-04-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jwt_auth", "0012_alter_user_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
