# Generated by Django 4.1.7 on 2023-07-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EvList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                ("power", models.FloatField(blank=True, default=None, null=True)),
                (
                    "postcode",
                    models.CharField(blank=True, default=None, max_length=7, null=True),
                ),
                (
                    "town",
                    models.CharField(
                        blank=True, default=None, max_length=25, null=True
                    ),
                ),
                (
                    "enabled",
                    models.CharField(blank=True, default=None, max_length=5, null=True),
                ),
                ("latitude", models.FloatField(blank=True, default=None, null=True)),
                ("longitude", models.FloatField(blank=True, default=None, null=True)),
                (
                    "fast_charging",
                    models.CharField(blank=True, default=None, max_length=5, null=True),
                ),
            ],
        ),
    ]
