# Generated by Django 4.1.7 on 2023-10-19 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Favourite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateField(auto_now_add=True)),
                (
                    "request_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("postcode", models.CharField(blank=True, max_length=10, null=True)),
                ("address", models.CharField(blank=True, max_length=50, null=True)),
                ("channel", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "primary_schools",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "scondary_schools",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                ("tubes", models.SmallIntegerField(blank=True, default=0, null=True)),
                ("trains", models.SmallIntegerField(blank=True, default=0, null=True)),
                ("evs", models.SmallIntegerField(blank=True, default=0, null=True)),
                (
                    "restaurants",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                ("pubs", models.SmallIntegerField(blank=True, default=0, null=True)),
                ("parks", models.SmallIntegerField(blank=True, default=0, null=True)),
                ("gyms", models.SmallIntegerField(blank=True, default=0, null=True)),
                (
                    "supermarkets",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                ("crime", models.SmallIntegerField(blank=True, default=0, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listing_favourites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
