# Generated by Django 4.1.5 on 2023-01-27 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0003_property_tenure'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.PositiveIntegerField(blank=True, default=None)),
                ('prop_long', models.FloatField(blank=True, default=None, null=True)),
                ('prop_lat', models.FloatField(blank=True, default=None, null=True)),
                ('restaurant_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('cuisine_value', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('Rating', models.FloatField(blank=True, default=None, null=True)),
                ('source_value', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('POI_lat', models.FloatField(blank=True, default=None, null=True)),
                ('POI_long', models.FloatField(blank=True, default=None, null=True)),
                ('adjusted_dist_km', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, null=True)),
                ('walking_time_mins', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, null=True)),
                ('property_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='properties.property')),
            ],
        ),
    ]
