# Generated by Django 4.1.5 on 2023-01-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyrestaurant',
            name='adjusted_dist_km',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='propertyrestaurant',
            name='cuisine_value',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertyrestaurant',
            name='source_value',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertyrestaurant',
            name='walking_time_mins',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, null=True),
        ),
    ]
