# Generated by Django 4.1.3 on 2023-01-03 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySearch',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_search', models.BooleanField(default=True)),
                ('search_name', models.TextField(blank=True, default=None, null=True)),
                ('restaurant_selection', models.BooleanField(blank=True, default=False, null=True)),
                ('restaurant_decision', models.CharField(blank=True, default=False, max_length=15, null=True)),
                ('restaurant_distance', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('restaurant_cuisine_1', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('restaurant_cuisine_2', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('takeaway_selection', models.BooleanField(blank=True, default=False, null=True)),
                ('takeaway_decision', models.CharField(blank=True, default=False, max_length=15, null=True)),
                ('takeaway_distance', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('takeaway_cuisine_1', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('takeaway_cuisine_2', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('pubs_selection', models.BooleanField(blank=True, default=False, null=True)),
                ('pubs_distance', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cafes_selection', models.BooleanField(blank=True, default=False, null=True)),
                ('cafes_decision', models.CharField(blank=True, default=False, max_length=15, null=True)),
                ('cafes_detail', models.CharField(blank=True, default=False, max_length=15, null=True)),
                ('cafes_distance', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('tube_selection', models.BooleanField(blank=True, default=False, null=True)),
                ('tube_decision', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('tube_detail', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('tube_distance', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('train_selection', models.BooleanField(blank=True, default=False, null=True)),
                ('train_decision', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('train_detail', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('train_distance', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('primary_selection', models.BooleanField(blank=True, default=False, null=True)),
                ('primary_religion', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('primary_mode', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('primary_distance', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('secondary_selection', models.BooleanField(blank=True, default=False, null=True)),
                ('secondary_religion', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('secondary_mode', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('secondary_distance', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('college_selection', models.BooleanField(blank=True, default=False, null=True)),
                ('college_religion', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('college_mode', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('college_distance', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('supermarket_selection', models.BooleanField(blank=True, default=False, null=True)),
                ('supermarket_decision', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('supermarket_segment', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('supermarket_size', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('supermarket_distance', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('gym_selection', models.BooleanField(blank=True, default=False, null=True)),
                ('gym_studio_name', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('gym_class_type', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('gym_distance', models.PositiveIntegerField(blank=True, default=False, null=True)),
                ('park_selection', models.BooleanField(blank=True, default=False, null=True)),
                ('park_type', models.CharField(blank=True, default=False, max_length=100, null=True)),
                ('park_distance', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('workplace_selection', models.BooleanField(blank=True, default=False, null=True)),
                ('workplace_detail', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('workplace_transport', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('workplace_distance', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('family_selection', models.BooleanField(blank=True, default=False, null=True)),
                ('famly_detail_1', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('family_distance_1', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('famly_detail_2', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('family_distance_2', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('famly_detail_3', models.CharField(blank=True, default=False, max_length=30, null=True)),
                ('family_distance_3', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('property_price_min', models.PositiveBigIntegerField(blank=True, default=False, null=True)),
                ('property_price_max', models.PositiveBigIntegerField(blank=True, default=False, null=True)),
                ('property_bed_min', models.PositiveBigIntegerField(blank=True, default=False, null=True)),
                ('property_bed_max', models.PositiveBigIntegerField(blank=True, default=False, null=True)),
                ('property_type', models.CharField(blank=True, default=False, max_length=20, null=True)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_search_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
