# Generated by Django 4.1.3 on 2023-01-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_search_details', '0002_propertysearch_average_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysearch',
            name='search_type',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
