# Generated by Django 4.1.3 on 2023-01-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_search_details', '0004_remove_propertysearch_cafes_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysearch',
            name='total_properties',
            field=models.PositiveBigIntegerField(blank=True, default=False, null=True),
        ),
    ]
