# Generated by Django 4.1.3 on 2023-01-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_search_details', '0005_propertysearch_total_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysearch',
            name='search_channel',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
