# Generated by Django 4.1.5 on 2023-01-31 17:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property_search_details', '0006_propertysearch_search_channel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='propertysearch',
            unique_together={('owner', 'search_name')},
        ),
    ]
