# Generated by Django 4.1.5 on 2023-02-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_search_details', '0007_alter_propertysearch_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertysearch',
            name='train_decision',
            field=models.CharField(blank=True, default=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='propertysearch',
            name='train_detail',
            field=models.CharField(blank=True, default=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='propertysearch',
            name='tube_decision',
            field=models.CharField(blank=True, default=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='propertysearch',
            name='tube_detail',
            field=models.CharField(blank=True, default=False, max_length=200, null=True),
        ),
    ]
