# Generated by Django 4.1.5 on 2023-02-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_search_details', '0008_alter_propertysearch_train_decision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysearch',
            name='family_mode_1',
            field=models.CharField(blank=True, default=False, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='propertysearch',
            name='family_mode_2',
            field=models.CharField(blank=True, default=False, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='propertysearch',
            name='family_mode_3',
            field=models.CharField(blank=True, default=False, max_length=30, null=True),
        ),
    ]
