# Generated by Django 4.1.5 on 2023-02-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_search_details', '0009_propertysearch_family_mode_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertysearch',
            old_name='famly_detail_1',
            new_name='family_detail_1',
        ),
        migrations.RenameField(
            model_name='propertysearch',
            old_name='famly_detail_2',
            new_name='family_detail_2',
        ),
        migrations.RenameField(
            model_name='propertysearch',
            old_name='famly_detail_3',
            new_name='family_detail_3',
        ),
    ]
