# Generated by Django 4.1.5 on 2023-02-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_search_details', '0010_rename_famly_detail_1_propertysearch_family_detail_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertysearch',
            name='cafes_decision',
            field=models.CharField(blank=True, default=False, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='propertysearch',
            name='cafes_detail',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertysearch',
            name='gym_studio_name',
            field=models.CharField(blank=True, default=False, max_length=50, null=True),
        ),
    ]
