# Generated by Django 4.1.5 on 2023-02-06 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property_search_details', '0011_alter_propertysearch_cafes_decision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertysearch',
            name='owner',
            field=models.ForeignKey(blank=True, default=31, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_search_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
