# Generated by Django 4.1.7 on 2023-10-10 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Usage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "package",
                    models.CharField(
                        blank=True, default=False, max_length=20, null=True
                    ),
                ),
                (
                    "epc_tier",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "epc_total_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "epc_monthly_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "listing_tier",
                    models.SmallIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "listing_total_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "listing_monthly_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("last_update_month", models.IntegerField(blank=True, null=True)),
                ("last_update_year", models.IntegerField(blank=True, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
