# Generated by Django 4.1.7 on 2023-10-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_details", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usage",
            name="listing_ai_total",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="usage",
            name="listing_insight_total",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="usage",
            name="listing_normal_total",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="usage",
            name="valuation_monthly_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="usage",
            name="valuation_tier",
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="usage",
            name="valuation_total_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
