# Generated by Django 4.1.5 on 2023-11-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "account_details",
            "0002_usage_listing_ai_total_usage_listing_insight_total_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="usage",
            name="last_login",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="usage",
            name="total_logins",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
