# Generated by Django 4.1.5 on 2023-11-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_details", "0003_usage_last_login_usage_total_logins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usage",
            name="last_login",
            field=models.DateField(blank=True, null=True),
        ),
    ]
