# Generated by Django 4.1.5 on 2024-01-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_details", "0005_alter_usage_id_alter_usage_last_login_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usage",
            name="package",
            field=models.CharField(
                blank=True, default="Advanced Pilot", max_length=20, null=True
            ),
        ),
    ]
