# Generated by Django 4.1.5 on 2024-03-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_details", "0006_alter_usage_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="usage",
            name="save_lead_gen_month",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="usage",
            name="save_lead_gen_total",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
