# Generated by Django 4.1.5 on 2024-03-08 09:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account_details", "0007_usage_save_lead_gen_month_usage_save_lead_gen_total"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usage",
            old_name="save_lead_gen_month",
            new_name="save_lead_gen_month_total",
        ),
    ]
