# Generated by Django 4.1.5 on 2024-03-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "account_details",
            "0008_rename_save_lead_gen_month_usage_save_lead_gen_month_total",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="usage",
            name="package",
            field=models.CharField(
                blank=True, default="Free", max_length=20, null=True
            ),
        ),
    ]
