# Generated by Django 4.1.5 on 2024-04-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account_details", "0009_alter_usage_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="usage",
            name="credits",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="usage",
            name="last_payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usage",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
