# Generated by Django 4.1.7 on 2023-07-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Postcodes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "postcode",
                    models.CharField(blank=True, default=None, max_length=7, null=True),
                ),
                ("longitude", models.FloatField(default=None)),
                ("latitude", models.FloatField(default=None)),
                ("easting", models.IntegerField(default=None)),
                ("northing", models.IntegerField(default=None)),
                (
                    "district",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "ward",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "lsoa",
                    models.CharField(
                        blank=True, default=None, max_length=40, null=True
                    ),
                ),
                (
                    "avg_income",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
            ],
        ),
    ]
