# Generated by Django 4.1.7 on 2023-07-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcodes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postcodes",
            name="ward",
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
