# Generated by Django 4.1.7 on 2023-08-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borough",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "ward",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "ward_avg_price",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "ward_transactions",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
            ],
        ),
    ]
