# Generated by Django 4.1.5 on 2024-04-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Outcodes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outcode",
                    models.CharField(blank=True, default=None, max_length=4, null=True),
                ),
            ],
        ),
    ]
