# Generated by Django 4.1.5 on 2023-01-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_primaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyprimary',
            name='school_id',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
