# Generated by Django 4.1.3 on 2023-01-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='channel',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='council_tax',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='monthly',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='sqft',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
