# Generated by Django 4.1.3 on 2023-01-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_channel_property_council_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='tenure',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
