# Generated by Django 4.1.3 on 2023-01-03 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySearchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_score', models.FloatField(blank=True, default=None, null=True)),
                ('takeaway_score', models.FloatField(blank=True, default=None, null=True)),
                ('pubs_score', models.FloatField(blank=True, default=None, null=True)),
                ('cafes_score', models.FloatField(blank=True, default=None, null=True)),
                ('tube_score', models.FloatField(blank=True, default=None, null=True)),
                ('train_score', models.FloatField(blank=True, default=None, null=True)),
                ('primary_score', models.FloatField(blank=True, default=None, null=True)),
                ('secondary_score', models.FloatField(blank=True, default=None, null=True)),
                ('college_score', models.FloatField(blank=True, default=None, null=True)),
                ('supermarket_score', models.FloatField(blank=True, default=None, null=True)),
                ('gym_score', models.FloatField(blank=True, default=None, null=True)),
                ('park_score', models.FloatField(blank=True, default=None, null=True)),
                ('workplace_score', models.FloatField(blank=True, default=None, null=True)),
                ('friends_score', models.FloatField(blank=True, default=None, null=True)),
                ('total_score', models.FloatField(blank=True, default=None, null=True)),
                ('average_score', models.FloatField(blank=True, default=None, null=True)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_search_scores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
