# Generated by Django 4.1.7 on 2023-03-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pub_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Pub_category', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Pub_address', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Pub_street', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('Pub_town', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Pub_postcode', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Website', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Contact', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('url', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Lat', models.FloatField(blank=True, default=None, null=True)),
                ('long', models.FloatField(blank=True, default=None, null=True)),
                ('Postcode_area', models.CharField(blank=True, default=None, max_length=15, null=True)),
            ],
        ),
    ]
