# Generated by Django 4.1.7 on 2023-03-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_pubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='Website',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
