# Generated by Django 4.1.7 on 2023-03-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_pubs', '0002_alter_pub_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='Pub_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
