# Generated by Django 4.1.7 on 2023-07-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SecondaryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urn", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "local_authority",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "school_name",
                    models.CharField(
                        blank=True, default=None, max_length=150, null=True
                    ),
                ),
                (
                    "school_type",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "primary_flag",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "secondary_flag",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "sixth_form_flag",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True, default=None, max_length=10, null=True
                    ),
                ),
                (
                    "religion",
                    models.CharField(
                        blank=True, default=None, max_length=40, null=True
                    ),
                ),
                (
                    "admissions_policy",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "ofsted_results",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                ("last_ofsted", models.DateField(blank=True, default=None, null=True)),
                ("latitude", models.FloatField(blank=True, default=None, null=True)),
                ("longitude", models.FloatField(blank=True, default=None, null=True)),
                ("places", models.FloatField(blank=True, default=None, null=True)),
                (
                    "applications",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "min_distance",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "max_distance",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "other_info",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "total_pass_rate",
                    models.FloatField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "total_top_rate",
                    models.FloatField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                ("percentile", models.FloatField(blank=True, default=None, null=True)),
                (
                    "borough_percentile",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "non_independent_percentile",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "borough_non_independent_percentile",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "school_url",
                    models.CharField(
                        blank=True, default=None, max_length=300, null=True
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True, default=None, max_length=500, null=True
                    ),
                ),
            ],
        ),
    ]
