# Generated by Django 4.1.7 on 2023-08-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wittle_secondary_details", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secondarydetail",
            name="school_type",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
