# Generated by Django 4.1.7 on 2023-09-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wittle_secondary_details", "0002_alter_secondarydetail_school_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="secondarydetail",
            name="other_info",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
