# Generated by Django 4.1.7 on 2023-03-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='living',
            name='admin_status',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='amazon_provider',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='amazon_status',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='amazon_value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='apple_provider',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='apple_status',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='apple_value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='boiler_provider',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='boiler_status',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='boiler_value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='broadband_provider',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='broadband_status',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='broadband_value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='bt_provider',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='bt_status',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='bt_value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='council_tax_status',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='council_tax_value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='disney_provider',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='disney_status',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='disney_value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='electric_provider',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='electric_value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='energy_detail',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='energy_provider',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='energy_status',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='energy_value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='gas_provider',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='gas_value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='gym_provider',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='gym_status',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='gym_value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='insurance_provider',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='insurance_status',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='insurance_value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='mortgage_provider',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='mortgage_status',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='mortgage_value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='netflix_provider',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='netflix_status',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='netflix_value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='nowtv_provider',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='nowtv_status',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='nowtv_value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='other_provider_1',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='other_provider_2',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='other_provider_3',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='other_status_1',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='other_status_2',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='other_status_3',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='other_value_1',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='other_value_2',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='other_value_3',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='sky_provider',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='sky_status',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='sky_value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='tv_status',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='tv_value',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
