# Generated by Django 4.1.7 on 2023-03-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_details', '0002_alter_living_admin_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='living',
            name='lifestyle_status',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='living',
            name='postcode',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='living',
            name='property_status',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='living',
            name='subscription_type',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
    ]
