# Generated by Django 4.1.5 on 2023-04-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_details', '0002_living_rent_date_living_rent_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='living',
            name='email_status',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
    ]
