# Generated by Django 4.1.5 on 2023-04-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_details', '0003_living_email_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='living',
            name='postcode',
        ),
        migrations.AddField(
            model_name='living',
            name='lat',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='living',
            name='long',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
