# Generated by Django 4.1.7 on 2023-03-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_details', '0003_living_lifestyle_status_living_postcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='living',
            old_name='bt_date',
            new_name='phone_date',
        ),
        migrations.RenameField(
            model_name='living',
            old_name='amazon_provider',
            new_name='phone_provider',
        ),
        migrations.RenameField(
            model_name='living',
            old_name='bt_status',
            new_name='phone_status',
        ),
        migrations.RenameField(
            model_name='living',
            old_name='bt_value',
            new_name='phone_value',
        ),
        migrations.RemoveField(
            model_name='living',
            name='apple_provider',
        ),
        migrations.RemoveField(
            model_name='living',
            name='bt_provider',
        ),
        migrations.RemoveField(
            model_name='living',
            name='disney_provider',
        ),
        migrations.RemoveField(
            model_name='living',
            name='netflix_provider',
        ),
        migrations.RemoveField(
            model_name='living',
            name='nowtv_date',
        ),
        migrations.RemoveField(
            model_name='living',
            name='nowtv_provider',
        ),
        migrations.RemoveField(
            model_name='living',
            name='nowtv_status',
        ),
        migrations.RemoveField(
            model_name='living',
            name='nowtv_value',
        ),
        migrations.RemoveField(
            model_name='living',
            name='sky_provider',
        ),
        migrations.AddField(
            model_name='living',
            name='other_type_1',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='living',
            name='other_type_2',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='living',
            name='other_type_3',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
