# Generated by Django 4.1.5 on 2023-04-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_details', '0004_remove_living_postcode_living_lat_living_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='living',
            name='admin_populated',
            field=models.SmallIntegerField(blank=True, default=False, null=True),
        ),
    ]
