# Generated by Django 4.1.7 on 2023-03-27 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('living_details', '0004_rename_bt_date_living_phone_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='living',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='living_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
