# Generated by Django 4.1.7 on 2023-03-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_details', '0006_alter_living_amazon_value_alter_living_apple_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='living',
            name='email_address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='living',
            name='postcode',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
