# Generated by Django 4.1.7 on 2023-03-27 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('living_details', '0007_alter_living_email_address_alter_living_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='living',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='living_details', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
