# Generated by Django 4.1.5 on 2024-03-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign_tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracker",
            name="date_added",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tracker",
            name="launch_price",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
