# Generated by Django 4.1.5 on 2024-04-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign_tracking", "0002_tracker_date_added_tracker_launch_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracker",
            name="pdf",
            field=models.CharField(blank=True, default=None, max_length=600, null=True),
        ),
    ]
