# Generated by Django 4.1.5 on 2024-04-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign_tracking", "0004_alter_tracker_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracker",
            name="status_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
