# Generated by Django 4.1.5 on 2024-04-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign_tracking", "0005_tracker_status_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracker",
            name="target_rightmove_id",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
