# Generated by Django 4.1.5 on 2024-04-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign_tracking", "0006_tracker_target_rightmove_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracker",
            name="logic_app_run_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
