# Generated by Django 4.1.5 on 2024-04-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign_tracking", "0007_tracker_logic_app_run_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tracker",
            name="logic_app_run_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
