# Generated by Django 4.1.5 on 2024-04-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign_tracking", "0008_alter_tracker_logic_app_run_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracker",
            name="stannp_cost_response",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
