# Generated by Django 4.1.7 on 2023-10-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client_list", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="hierarchy",
        ),
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
