# Generated by Django 4.1.5 on 2024-03-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client_list", "0002_remove_company_hierarchy_alter_company_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
