# Generated by Django 4.1.5 on 2023-01-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_gyms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertygym',
            name='property_postcode',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
