# Generated by Django 4.1.5 on 2024-03-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letter_campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaigns",
            name="campaign_status",
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
