# Generated by Django 4.1.5 on 2024-04-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letter_campaigns", "0002_campaigns_campaign_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaigns",
            name="campaign_name",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
