# Generated by Django 4.1.5 on 2024-01-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_search_searches", "0003_alter_agentsearches_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentsearches",
            name="size",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
    ]
