# Generated by Django 4.1.5 on 2024-01-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_search_searches", "0004_alter_agentsearches_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentsearches",
            name="search_type",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
