# Generated by Django 4.1.3 on 2023-01-03 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySecondary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.PositiveIntegerField(blank=True, default=None)),
                ('property_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('prop_long', models.FloatField(blank=True, default=None, null=True)),
                ('prop_lat', models.FloatField(blank=True, default=None, null=True)),
                ('school_id', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('school_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('postcode', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('postcode_area', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('school_grouping', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('religious_grouping', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ofsted_results', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ofsted_recency', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('alternative_ofsted', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('POI_long', models.FloatField(blank=True, default=None, null=True)),
                ('POI_lat', models.FloatField(blank=True, default=None, null=True)),
                ('straight_dist_km', models.FloatField(blank=True, default=None, null=True)),
                ('adjusted_dist_km', models.FloatField(blank=True, default=None, null=True)),
                ('walking_time_mins', models.FloatField(blank=True, default=None, null=True)),
                ('driving_time_mins', models.FloatField(blank=True, default=None, null=True)),
                ('cycling_time_mins', models.FloatField(blank=True, default=None, null=True)),
                ('property_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondaries', to='properties.property')),
            ],
        ),
    ]
