# Generated by Django 4.1.5 on 2023-01-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_secondaries', '0003_remove_propertysecondary_property_postcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertysecondary',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='propertysecondary',
            old_name='postcode',
            new_name='Postcode',
        ),
        migrations.RenameField(
            model_name='propertysecondary',
            old_name='postcode_area',
            new_name='Postcode_area',
        ),
        migrations.AlterField(
            model_name='propertysecondary',
            name='school_id',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
