# Generated by Django 4.1.7 on 2023-03-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode_district', models.CharField(blank=True, default=None, max_length=4, null=True)),
                ('postcode_area', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('overall_area', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('lat', models.FloatField(blank=True, default=None, null=True)),
                ('long', models.FloatField(blank=True, default=None, null=True)),
                ('surrounding_areas', models.CharField(blank=True, default=None, max_length=40, null=True)),
            ],
        ),
    ]
