# Generated by Django 4.1.7 on 2023-03-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcode_locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='surrounding_areas',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
