# Generated by Django 4.1.7 on 2023-03-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcode_locations', '0002_alter_location_surrounding_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='surrounding_areas',
            field=models.CharField(blank=True, default=None, max_length=75, null=True),
        ),
    ]
