# Generated by Django 4.1.5 on 2023-01-27 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0003_property_tenure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(blank=True, default=False, max_length=250, null=True)),
                ('restaurant_score', models.FloatField(blank=True, default=None, null=True)),
                ('takeaway_score', models.FloatField(blank=True, default=None, null=True)),
                ('pubs_score', models.FloatField(blank=True, default=None, null=True)),
                ('cafes_score', models.FloatField(blank=True, default=None, null=True)),
                ('tube_score', models.FloatField(blank=True, default=None, null=True)),
                ('train_score', models.FloatField(blank=True, default=None, null=True)),
                ('primary_score', models.FloatField(blank=True, default=None, null=True)),
                ('secondary_score', models.FloatField(blank=True, default=None, null=True)),
                ('college_score', models.FloatField(blank=True, default=None, null=True)),
                ('supermarket_score', models.FloatField(blank=True, default=None, null=True)),
                ('gym_score', models.FloatField(blank=True, default=None, null=True)),
                ('park_score', models.FloatField(blank=True, default=None, null=True)),
                ('workplace_score', models.FloatField(blank=True, default=None, null=True)),
                ('friends_score', models.FloatField(blank=True, default=None, null=True)),
                ('total_score', models.FloatField(blank=True, default=None, null=True)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='properties.property')),
            ],
        ),
    ]
