# Generated by Django 4.1.3 on 2023-01-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites_properties', '0002_favourite_cafes_score_favourite_college_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='favourite',
        ),
        migrations.AddField(
            model_name='favourite',
            name='property_name',
            field=models.CharField(blank=True, default=False, max_length=250, null=True),
        ),
    ]
