# Generated by Django 4.1.5 on 2023-02-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites_properties', '0002_favourite_cafes_input_favourite_college_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='cafes_selection',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='favourite',
            name='college_selection',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='favourite',
            name='friends_selection',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='favourite',
            name='gym_selection',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='favourite',
            name='park_selection',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='favourite',
            name='primary_selection',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='favourite',
            name='pubs_selection',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='favourite',
            name='restaurant_selection',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='favourite',
            name='secondary_selection',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='favourite',
            name='supermarket_selection',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='favourite',
            name='takeaway_selection',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='favourite',
            name='train_selection',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='favourite',
            name='tube_selection',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='favourite',
            name='workplace_selection',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
