# Generated by Django 4.1.5 on 2023-02-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites_properties', '0003_favourite_cafes_selection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='search_name',
            field=models.CharField(blank=True, default=False, max_length=100, null=True),
        ),
    ]
