# Generated by Django 4.1.5 on 2023-02-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites_properties', '0004_favourite_search_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='search_type',
            field=models.CharField(blank=True, default=False, max_length=10, null=True),
        ),
    ]
