# Generated by Django 4.1.5 on 2024-01-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonaDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        blank=True, default=None, max_length=1000, null=True
                    ),
                ),
                ("latitude", models.FloatField(blank=True, default=None, null=True)),
                ("longitude", models.FloatField(blank=True, default=None, null=True)),
                (
                    "lsoa",
                    models.CharField(
                        blank=True, default=None, max_length=40, null=True
                    ),
                ),
                (
                    "young_families",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "young_professionals",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                ("vibes", models.FloatField(blank=True, default=None, null=True)),
                (
                    "commuter_convenience",
                    models.FloatField(blank=True, default=None, null=True),
                ),
            ],
        ),
    ]
