# Generated by Django 4.1.5 on 2024-01-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("postcode_personas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personadetails",
            name="postcode",
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=1000, null=True
            ),
        ),
    ]
