# Generated by Django 4.1.5 on 2024-01-13 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("postcode_personas", "0002_alter_personadetails_postcode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personadetails",
            old_name="lsoa",
            new_name="district",
        ),
        migrations.RemoveField(
            model_name="personadetails",
            name="commuter_convenience",
        ),
        migrations.RemoveField(
            model_name="personadetails",
            name="vibes",
        ),
        migrations.RemoveField(
            model_name="personadetails",
            name="young_families",
        ),
        migrations.RemoveField(
            model_name="personadetails",
            name="young_professionals",
        ),
    ]
