# Generated by Django 4.1.7 on 2023-03-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Takeaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('adjusted_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('cuisine', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('total_reviews', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, null=True)),
                ('wittle_rating', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, null=True)),
                ('lat', models.FloatField(blank=True, default=None, null=True)),
                ('long', models.FloatField(blank=True, default=None, null=True)),
                ('postcode_area', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('url', models.CharField(blank=True, default=None, max_length=150, null=True)),
            ],
        ),
    ]
