# Generated by Django 4.1.7 on 2023-03-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_takeaways', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeaway',
            name='total_reviews',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=6, null=True),
        ),
    ]
