# Generated by Django 4.1.7 on 2023-03-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_takeaways', '0002_alter_takeaway_total_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeaway',
            name='cuisine',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
