# Generated by Django 4.1.7 on 2023-03-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_takeaways', '0004_alter_takeaway_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeaway',
            name='postcode_area',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
