# Generated by Django 4.1.7 on 2023-03-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_takeaways', '0005_alter_takeaway_postcode_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeaway',
            name='postcode',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='takeaway',
            name='postcode_area',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
