# Generated by Django 4.1.7 on 2023-03-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_takeaways', '0007_alter_takeaway_postcode_alter_takeaway_postcode_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takeaway',
            name='adjusted_name',
        ),
        migrations.AlterField(
            model_name='takeaway',
            name='postcode',
            field=models.CharField(blank=True, default=None, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='takeaway',
            name='postcode_area',
            field=models.CharField(blank=True, default=None, max_length=11, null=True),
        ),
    ]
