# Generated by Django 4.1.7 on 2023-03-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_takeaways', '0008_remove_takeaway_adjusted_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeaway',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
