# Generated by Django 4.1.7 on 2023-03-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_takeaways', '0009_alter_takeaway_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeaway',
            name='postcode',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='takeaway',
            name='postcode_area',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
