# Generated by Django 4.1.5 on 2023-03-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_colleges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='students',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True),
        ),
    ]
