# Generated by Django 4.1.5 on 2024-02-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, default=None, max_length=400, null=True
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                ("bathrooms", models.FloatField(blank=True, default=None, null=True)),
                ("bedrooms", models.FloatField(blank=True, default=None, null=True)),
                (
                    "agent",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "propertyType",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "tenure",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                ("longitude", models.FloatField(blank=True, default=None, null=True)),
                ("latitude", models.FloatField(blank=True, default=None, null=True)),
                (
                    "postcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "incode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "outcode",
                    models.CharField(
                        blank=True, default=None, max_length=10, null=True
                    ),
                ),
                (
                    "subcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
