# Generated by Django 4.1.5 on 2024-02-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sold_properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="uprn",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
