# Generated by Django 4.1.7 on 2023-07-05 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("postcodes", "0002_alter_postcodes_ward"),
    ]

    operations = [
        migrations.CreateModel(
            name="TubeSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "postcode",
                    models.CharField(blank=True, default=None, max_length=7, null=True),
                ),
                (
                    "tube_10_mins",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("percentile", models.FloatField(blank=True, default=None, null=True)),
                (
                    "postcode_ref",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tubes",
                        to="postcodes.postcodes",
                    ),
                ),
            ],
        ),
    ]
