# Generated by Django 4.1.7 on 2023-10-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "postcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "current_energy_efficiency",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "potential_energy_efficiency",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "current_energy_rating",
                    models.CharField(
                        blank=True, db_index=True, default=None, max_length=2, null=True
                    ),
                ),
                (
                    "potential_energy_rating",
                    models.CharField(
                        blank=True, db_index=True, default=None, max_length=2, null=True
                    ),
                ),
                (
                    "floor_area",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "final_floor_level",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "inspection_date",
                    models.DateField(blank=True, default=None, null=True),
                ),
            ],
        ),
    ]
