# Generated by Django 4.1.7 on 2023-10-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="floor_area",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
