# Generated by Django 4.1.7 on 2023-10-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="postcode",
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=10, null=True
            ),
        ),
    ]
