# Generated by Django 4.1.5 on 2023-11-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc", "0003_alter_data_current_energy_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="current_energy_efficiency",
            field=models.SmallIntegerField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="data",
            name="potential_energy_efficiency",
            field=models.SmallIntegerField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
    ]
