# Generated by Django 4.1.5 on 2023-11-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rightmove_id",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True, unique=True
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, default=None, max_length=400, null=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "displayAddress",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                ("bathrooms", models.FloatField(blank=True, default=None, null=True)),
                ("bedrooms", models.FloatField(blank=True, default=None, null=True)),
                (
                    "agent",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "propertyType",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "secondary_price",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, default=None, max_length=10, null=True
                    ),
                ),
                (
                    "tenure",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "images",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "epc",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "addedOn",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "let_available_date",
                    models.CharField(
                        blank=True, default=None, max_length=15, null=True
                    ),
                ),
                (
                    "let_type",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "furnish_type",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                ("deposit", models.FloatField(blank=True, default=None, null=True)),
                ("size", models.FloatField(blank=True, default=None, null=True)),
                ("longitude", models.FloatField(blank=True, default=None, null=True)),
                ("latitude", models.FloatField(blank=True, default=None, null=True)),
                (
                    "postcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "date_added_db",
                    models.DateField(blank=True, default=None, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
            ],
        ),
    ]
