# Generated by Django 4.1.5 on 2023-11-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_property_rental", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="furnish_type",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="let_type",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
