# Generated by Django 4.1.5 on 2023-11-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_property_rental", "0005_alter_property_current_epc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="added_revised",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="reduced_revised",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
