# Generated by Django 4.1.5 on 2023-11-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_property_rental", "0008_property_week_taken_off_market"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="price_numeric",
            field=models.FloatField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
