# Generated by Django 4.1.5 on 2023-11-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_property_rental", "0010_alter_property_deposit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="size",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
