# Generated by Django 4.1.5 on 2023-11-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_property_rental", "0011_alter_property_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="price",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
