# Generated by Django 4.1.5 on 2023-12-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_property_rental", "0013_property_incode_property_outcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="floorplan_url",
            field=models.CharField(blank=True, default=None, max_length=400, null=True),
        ),
    ]
