# Generated by Django 4.1.5 on 2024-01-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_property_rental", "0018_alter_property_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="price_history",
            field=models.CharField(
                blank=True, default=None, max_length=1500, null=True
            ),
        ),
    ]
