# Generated by Django 4.1.5 on 2024-02-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_property_rental", "0020_rename_price_history_property_pricehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="price_per_sqft",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
