# Generated by Django 4.1.5 on 2024-04-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_property_rental", "0021_property_price_per_sqft"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="displayAddress",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="epc",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="images",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="title",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
