# Generated by Django 4.1.5 on 2023-03-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('city_number', models.SmallIntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
