# Generated by Django 4.1.5 on 2023-03-31 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('living_master', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_number',
        ),
    ]
