# Generated by Django 4.1.5 on 2023-01-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('percentiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertypercentiles',
            old_name='all_primariess',
            new_name='all_primaries',
        ),
        migrations.RenameField(
            model_name='propertypercentiles',
            old_name='all_secondariess',
            new_name='all_secondaries',
        ),
        migrations.RenameField(
            model_name='propertypercentiles',
            old_name='london_borough_primariess',
            new_name='london_borough_primaries',
        ),
        migrations.RenameField(
            model_name='propertypercentiles',
            old_name='london_borough_secondariess',
            new_name='london_borough_secondaries',
        ),
        migrations.RenameField(
            model_name='propertypercentiles',
            old_name='london_region_primariess',
            new_name='london_region_primaries',
        ),
        migrations.RenameField(
            model_name='propertypercentiles',
            old_name='london_region_secondariess',
            new_name='london_region_secondaries',
        ),
    ]
