# Generated by Django 4.1.5 on 2023-01-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('percentiles', '0003_alter_propertypercentiles_bar_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypercentiles',
            name='primary_score',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
