# Generated by Django 4.1.5 on 2023-01-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('percentiles', '0004_alter_propertypercentiles_primary_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypercentiles',
            name='college_score',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='secondary_score',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
