# Generated by Django 4.1.5 on 2023-01-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('percentiles', '0005_alter_propertypercentiles_college_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertypercentiles',
            name='all_bars',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='all_colleges',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='all_gyms',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='all_parks',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='all_primaries',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='all_restaurants',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='all_secondaries',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='all_supermarkets',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='all_takeaways',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='all_tubes',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='bar_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='college_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='gym_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='london_borough_bars',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='london_borough_colleges',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='london_borough_gyms',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='london_borough_parks',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='london_borough_primaries',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='london_borough_restaurants',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='london_borough_secondaries',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='london_borough_supermarkets',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='london_borough_takeaways',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='london_borough_tubes',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='london_region_bars',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='london_region_colleges',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='london_region_gyms',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='london_region_parks',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='london_region_primaries',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='london_region_restaurants',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='london_region_secondaries',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='london_region_supermarkets',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='london_region_takeaways',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='london_region_tubes',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='park_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='primary_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='secondary_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='supermarket_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='takeaway_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertypercentiles',
            name='tube_score',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
