# Generated by Django 4.1.5 on 2024-04-15 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Templates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_number",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                ("template_name", models.CharField(max_length=50, unique=True)),
                (
                    "template_body_1",
                    models.CharField(blank=True, max_length=1200, null=True),
                ),
                (
                    "template_body_2",
                    models.CharField(blank=True, max_length=1200, null=True),
                ),
                (
                    "template_body_3",
                    models.CharField(blank=True, max_length=1200, null=True),
                ),
                (
                    "template_body_4",
                    models.CharField(blank=True, max_length=1200, null=True),
                ),
                (
                    "template_body_5",
                    models.CharField(blank=True, max_length=1200, null=True),
                ),
                (
                    "template_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("sender_name", models.BooleanField(default=False)),
                ("sender_company", models.BooleanField(default=False)),
                ("sender_role", models.BooleanField(default=False)),
                ("sender_mobile", models.BooleanField(default=False)),
                ("sender_landline", models.BooleanField(default=False)),
                ("sender_email", models.BooleanField(default=False)),
                ("sender_website", models.BooleanField(default=False)),
                ("sender_footer", models.BooleanField(default=False)),
                ("logo_width", models.FloatField(blank=True, default=None, null=True)),
                ("logo_height", models.FloatField(blank=True, default=None, null=True)),
                (
                    "logo_position",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("opening", models.CharField(blank=True, max_length=40, null=True)),
                ("closing", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "example_pdf",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="letter_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
