# Generated by Django 4.1.5 on 2024-03-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letter_templates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templates",
            name="logo_position",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
