# Generated by Django 4.1.5 on 2024-03-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letter_templates", "0002_alter_templates_logo_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templates",
            name="template_body_1",
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name="templates",
            name="template_body_2",
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name="templates",
            name="template_body_3",
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name="templates",
            name="template_body_4",
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
