# Generated by Django 4.1.5 on 2024-03-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letter_templates", "0003_alter_templates_template_body_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="templates",
            name="template_body_5",
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
