# Generated by Django 4.1.5 on 2024-04-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letter_templates", "0004_templates_template_body_5"),
    ]

    operations = [
        migrations.AddField(
            model_name="templates",
            name="sender_footer",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
