# Generated by Django 4.1.5 on 2024-04-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letter_templates", "0005_templates_sender_footer"),
    ]

    operations = [
        migrations.AddField(
            model_name="templates",
            name="example_pdf",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
