# Generated by Django 4.1.5 on 2024-02-19 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sold_properties", "0002_property_uprn"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uprn", models.FloatField(blank=True, default=None, null=True)),
                ("sold_price", models.FloatField(blank=True, default=None, null=True)),
                ("sold_date", models.DateField(blank=True, default=None, null=True)),
                (
                    "property",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sold_prices",
                        to="sold_properties.property",
                    ),
                ),
            ],
        ),
    ]
