# Generated by Django 4.1.5 on 2024-03-23 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "letter_footer",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("mobile", models.FloatField(blank=True, default=None, null=True)),
                ("landline", models.FloatField(blank=True, default=None, null=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="letter_signatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
