# Generated by Django 4.1.5 on 2024-03-23 18:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("letter_signature_details", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signature",
            name="logo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
