# Generated by Django 4.1.5 on 2024-03-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letter_signature_details", "0002_signature_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signature",
            name="logo",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
