# Generated by Django 4.1.5 on 2024-03-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letter_signature_details", "0003_alter_signature_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="signature",
            name="role",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
