# Generated by Django 4.1.5 on 2024-04-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letter_signature_details", "0004_signature_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signature",
            name="landline",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="signature",
            name="mobile",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
