# Generated by Django 4.1.5 on 2024-04-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "letter_signature_details",
            "0005_alter_signature_landline_alter_signature_mobile",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="signature",
            name="website",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
