# Generated by Django 4.1.5 on 2024-05-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("letter_signature_details", "0006_signature_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="signature",
            name="banner_image",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="signature",
            name="digital_signature",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="signature",
            name="instagram",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="signature",
            name="qr_location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="signature",
            name="tiktok",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
