# Generated by Django 4.1.5 on 2024-05-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "letter_signature_details",
            "0007_signature_banner_image_signature_digital_signature_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="signature",
            name="profile_image",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
