# Generated by Django 4.1.7 on 2023-08-23 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("postcodes", "0002_alter_postcodes_ward"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "postcode",
                    models.CharField(blank=True, default=None, max_length=7, null=True),
                ),
                (
                    "restaurant_count",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "restaurant_score",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "normal_percentile",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "ward_percentile",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "borough_percentile",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "postcode_ref",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restaurants",
                        to="postcodes.postcodes",
                    ),
                ),
            ],
        ),
    ]
