# Generated by Django 4.1.7 on 2023-08-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gym_id",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "gym_name",
                    models.CharField(
                        blank=True, default=None, max_length=100, null=True
                    ),
                ),
                (
                    "gym_group",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "class_type",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "gym_address",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "gym_postcode",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, default=None, max_length=40, null=True
                    ),
                ),
                ("Lat", models.FloatField(blank=True, default=None, null=True)),
                ("long", models.FloatField(blank=True, default=None, null=True)),
                (
                    "url",
                    models.CharField(
                        blank=True, default=None, max_length=150, null=True
                    ),
                ),
            ],
        ),
    ]
