# Generated by Django 4.1.7 on 2023-03-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_id', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('gym_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('gym_group', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('class_type', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('gym_address', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('gym_postcode', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('Lat', models.FloatField(blank=True, default=None, null=True)),
                ('long', models.FloatField(blank=True, default=None, null=True)),
                ('url', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('Postcode_area', models.CharField(blank=True, default=None, max_length=4, null=True)),
            ],
        ),
    ]
