# Generated by Django 4.1.7 on 2023-03-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_gyms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='gym_postcode',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
