# Generated by Django 4.1.7 on 2023-10-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("living_gyms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gym",
            name="gym_group",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
