# Generated by Django 4.1.7 on 2023-03-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_gyms', '0002_alter_gym_gym_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='Postcode_area',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
