# Generated by Django 4.1.5 on 2023-04-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_gyms', '0004_gym_city_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
