# Generated by Django 4.1.7 on 2023-06-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_signup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentsignup",
            name="position",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
