# Generated by Django 4.1.5 on 2024-02-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_signup", "0003_alter_agentsignup_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentsignup",
            name="message",
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
