# Generated by Django 4.1.7 on 2023-07-19 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default=None, max_length=30, null=True
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                (
                    "postcode",
                    models.CharField(blank=True, default=None, max_length=7, null=True),
                ),
                ("latitude", models.FloatField(blank=True, default=None, null=True)),
                ("longitude", models.FloatField(blank=True, default=None, null=True)),
                ("price", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "type",
                    models.CharField(
                        blank=True, default=None, max_length=60, null=True
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "bedrooms",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "bathrooms",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "living_rooms",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, default=None, max_length=20, null=True
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="white_properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
