# Generated by Django 4.1.7 on 2023-10-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("white_properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="bathrooms",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
