# Generated by Django 4.1.7 on 2023-10-04 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("client_list", "0001_initial"),
        (
            "white_properties",
            "0003_alter_property_bedrooms_alter_property_living_rooms",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="property",
            name="agent",
        ),
        migrations.AddField(
            model_name="property",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="client_list.company",
            ),
        ),
    ]
