# Generated by Django 4.1.5 on 2023-04-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_secondaries', '0002_secondary_city_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondary',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=520, null=True),
        ),
    ]
