# Generated by Django 4.1.5 on 2023-04-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_secondaries', '0003_secondary_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondary',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=530, null=True),
        ),
    ]
