# Generated by Django 4.1.7 on 2023-10-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_favourites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favourite",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="favourite",
            name="address",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="favourite",
            name="postcode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="favourite",
            unique_together={("postcode", "address")},
        ),
    ]
