# Generated by Django 4.1.5 on 2023-11-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_favourites", "0003_favourite_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favourite",
            name="channel",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
