# Generated by Django 4.1.5 on 2023-11-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_favourites", "0004_alter_favourite_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="favourite",
            name="agent",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
