# Generated by Django 4.1.5 on 2023-11-13 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epc_favourites", "0007_alter_favourite_agent"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favourite",
            unique_together=set(),
        ),
    ]
