# Generated by Django 4.1.5 on 2023-11-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_favourites", "0008_alter_favourite_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="favourite",
            name="action",
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
