# Generated by Django 4.1.5 on 2023-11-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_favourites", "0010_alter_favourite_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favourite",
            name="rightmove_id",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
