# Generated by Django 4.1.5 on 2023-11-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_favourites", "0011_alter_favourite_rightmove_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="favourite",
            name="added_revised",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="favourite",
            name="reduced_revised",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
