# Generated by Django 4.1.5 on 2024-01-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_favourites", "0012_favourite_added_revised_favourite_reduced_revised"),
    ]

    operations = [
        migrations.AddField(
            model_name="favourite",
            name="emails_sent",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="favourite",
            name="letters_sent",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="favourite",
            name="notes",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="favourite",
            name="owner_email",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="favourite",
            name="owner_mobile",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="favourite",
            name="owner_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="favourite",
            name="valuation_booked",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
