# Generated by Django 4.1.5 on 2024-03-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_favourites", "0014_favourite_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="favourite",
            name="letter_sequence",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
