# Generated by Django 4.1.5 on 2024-04-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_favourites", "0016_favourite_letter_campaign"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favourite",
            name="valuation_booked",
        ),
        migrations.AddField(
            model_name="favourite",
            name="hand_cards",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
