# Generated by Django 4.1.5 on 2024-04-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_favourites", "0018_favourite_week_removed"),
    ]

    operations = [
        migrations.AddField(
            model_name="favourite",
            name="valuation_booked",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
