# Generated by Django 4.1.5 on 2024-04-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_favourites", "0019_favourite_valuation_booked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favourite",
            name="letter_campaign",
            field=models.CharField(
                blank=True, default="None", max_length=200, null=True
            ),
        ),
    ]
