# Generated by Django 4.1.5 on 2024-04-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_favourites", "0020_alter_favourite_letter_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="favourite",
            name="tracking",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
