# Generated by Django 4.1.5 on 2024-04-09 07:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epc_favourites", "0021_favourite_tracking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favourite",
            old_name="tracking",
            new_name="live_tracking",
        ),
    ]
