# Generated by Django 4.1.5 on 2024-04-09 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("epc_favourites", "0023_favourite_prce_numeric"),
    ]

    operations = [
        migrations.RenameField(
            model_name="favourite",
            old_name="prce_numeric",
            new_name="price_numeric",
        ),
    ]
