# Generated by Django 4.1.5 on 2024-04-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_favourites", "0024_rename_prce_numeric_favourite_price_numeric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favourite",
            name="owner_mobile",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
