# Generated by Django 4.1.7 on 2023-10-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_property_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="bathrooms",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="bedrooms",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
