# Generated by Django 4.1.7 on 2023-10-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_property_data", "0002_alter_property_bathrooms_alter_property_bedrooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="rightmove_id",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
