# Generated by Django 4.1.5 on 2023-11-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_property_data", "0003_alter_property_rightmove_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="rightmove_id",
            field=models.CharField(
                blank=True, default=None, max_length=20, null=True, unique=True
            ),
        ),
    ]
