# Generated by Django 4.1.5 on 2023-11-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_property_data", "0004_alter_property_rightmove_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="date_added_db",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="status",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
