# Generated by Django 4.1.5 on 2023-11-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_property_data", "0006_alter_property_date_added_db"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="current_epc",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="potential_epc",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
