# Generated by Django 4.1.5 on 2023-11-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_property_data", "0007_property_current_epc_property_potential_epc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="current_epc",
            field=models.IntegerField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="potential_epc",
            field=models.IntegerField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
    ]
