# Generated by Django 4.1.5 on 2023-11-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_property_data", "0009_property_added_revised_property_reduced_revised"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="week_taken_off_market",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
