# Generated by Django 4.1.5 on 2023-11-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_property_data", "0011_property_price_numeric"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="incode",
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="outcode",
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
