# Generated by Django 4.1.5 on 2024-01-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_property_data", "0013_property_floorplan_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="size",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
