# Generated by Django 4.1.5 on 2024-01-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("epc_property_data", "0015_property_subcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="current_letter",
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=2, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="potential_letter",
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=2, null=True
            ),
        ),
    ]
