# Generated by Django 4.1.7 on 2023-03-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Primary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('town', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('postcode', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('school_status', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('school_grouping', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('religious_grouping', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('ofsted_results', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('last_ofsted_inspection', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('students', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('ofsted_recency', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('alternative_ofsted', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('lat', models.FloatField(blank=True, default=None, null=True)),
                ('long', models.FloatField(blank=True, default=None, null=True)),
                ('postcode_area', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('url', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
    ]
