# Generated by Django 4.1.7 on 2023-03-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_primaries', '0002_alter_primary_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primary',
            name='religious_grouping',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
