# Generated by Django 4.1.7 on 2023-03-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('living_primaries', '0003_alter_primary_religious_grouping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primary',
            name='town',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
